/**
 * Sidebar themes, the way Slack does them: the colour mode (light/dark/system)
 * decides the message area, and a theme repaints the chrome around it — rail,
 * sidebar, top bar and the active-item highlight.
 *
 * Colours are matched by eye against Slack's swatches, so they are close
 * rather than exact.
 */
export interface ChromeTheme {
  id: string;
  name: string;
  group: string;
  /** Icon rail down the far left. */
  rail: string;
  /** Channel list. */
  sidebar: string;
  /** Top bar with the search box. */
  topbar: string;
  /** Selected channel. */
  active: string;
  text: string;
  muted: string;
  /** Unread badge and mention pill. */
  accent: string;
}

export const CHROME_THEME_GROUPS = [
  "Celebrate the music of Miles Davis",
  "Single color",
  "Vision assistive",
  "Fun and new",
  "Updated classics",
] as const;

export const CHROME_THEMES: ChromeTheme[] = [
  // ── Celebrate the music of Miles Davis ──
  {
    id: "kind-of-blue",
    name: "Kind of Blue",
    group: "Celebrate the music of Miles Davis",
    rail: "#1b3b5f",
    sidebar: "#20486f",
    topbar: "#1b3b5f",
    active: "#4a90c2",
    text: "#ffffff",
    muted: "#b9d3e8",
    accent: "#7cc0ea",
  },
  {
    id: "funky-fresh",
    name: "Funky Fresh",
    group: "Celebrate the music of Miles Davis",
    rail: "#2f6f63",
    sidebar: "#3a8578",
    topbar: "#2f6f63",
    active: "#7fc4a8",
    text: "#ffffff",
    muted: "#cfe8df",
    accent: "#a7e8cf",
  },
  {
    id: "jazz-club",
    name: "Jazz Club",
    group: "Celebrate the music of Miles Davis",
    rail: "#5c0f1c",
    sidebar: "#7a1424",
    topbar: "#5c0f1c",
    active: "#c0392b",
    text: "#ffffff",
    muted: "#e8c0c6",
    accent: "#ff8a80",
  },
  {
    id: "electric-fusion",
    name: "Electric Fusion",
    group: "Celebrate the music of Miles Davis",
    rail: "#3f7a2f",
    sidebar: "#4f9639",
    topbar: "#3f7a2f",
    active: "#8ed16b",
    text: "#ffffff",
    muted: "#d6ecc9",
    accent: "#b6f08c",
  },
  {
    id: "brassy",
    name: "Brassy",
    group: "Celebrate the music of Miles Davis",
    rail: "#7a5c12",
    sidebar: "#96721a",
    topbar: "#7a5c12",
    active: "#d1a63a",
    text: "#ffffff",
    muted: "#ecdcae",
    accent: "#f5d67a",
  },
  {
    id: "sunglasses-inside",
    name: "Sunglasses Inside",
    group: "Celebrate the music of Miles Davis",
    rail: "#3a0b33",
    sidebar: "#4d0f44",
    topbar: "#3a0b33",
    active: "#9b2b86",
    text: "#ffffff",
    muted: "#dcb8d5",
    accent: "#e07ecb",
  },

  // ── Single color ──
  {
    id: "aubergine",
    name: "Aubergine",
    group: "Single color",
    rail: "#350d36",
    sidebar: "#3f0e40",
    topbar: "#350d36",
    active: "#1164a3",
    text: "#ffffff",
    muted: "#cfc3cf",
    accent: "#eb4d5c",
  },
  {
    id: "clementine",
    name: "Clementine",
    group: "Single color",
    rail: "#8c2f11",
    sidebar: "#a63a17",
    topbar: "#8c2f11",
    active: "#e2703a",
    text: "#ffffff",
    muted: "#f0cbb8",
    accent: "#ffb08a",
  },
  {
    id: "banana",
    name: "Banana",
    group: "Single color",
    rail: "#8a6512",
    sidebar: "#a37a18",
    topbar: "#8a6512",
    active: "#dcb43c",
    text: "#ffffff",
    muted: "#eddfb5",
    accent: "#ffd97d",
  },
  {
    id: "jade",
    name: "Jade",
    group: "Single color",
    rail: "#0f4c3a",
    sidebar: "#146049",
    topbar: "#0f4c3a",
    active: "#2e9e77",
    text: "#ffffff",
    muted: "#bfe0d4",
    accent: "#6fdcb2",
  },
  {
    id: "lagoon",
    name: "Lagoon",
    group: "Single color",
    rail: "#0e3d54",
    sidebar: "#134f6c",
    topbar: "#0e3d54",
    active: "#2b87b5",
    text: "#ffffff",
    muted: "#bcd8e6",
    accent: "#6cc6ec",
  },
  {
    id: "barbra",
    name: "Barbra",
    group: "Single color",
    rail: "#6b0f2a",
    sidebar: "#8a1436",
    topbar: "#6b0f2a",
    active: "#c93a63",
    text: "#ffffff",
    muted: "#eec2d0",
    accent: "#ff85a8",
  },
  {
    id: "gray",
    name: "Gray",
    group: "Single color",
    rail: "#1d1f21",
    sidebar: "#26282b",
    topbar: "#1d1f21",
    active: "#4a4d51",
    text: "#ffffff",
    muted: "#b3b6b9",
    accent: "#9aa0a6",
  },
  {
    id: "mood-indigo",
    name: "Mood Indigo",
    group: "Single color",
    rail: "#1b1f6b",
    sidebar: "#242a85",
    topbar: "#1b1f6b",
    active: "#4d55c9",
    text: "#ffffff",
    muted: "#c3c6ea",
    accent: "#8f97ff",
  },

  // ── Vision assistive ──
  {
    id: "tritanopia",
    name: "Tritanopia",
    group: "Vision assistive",
    rail: "#101112",
    sidebar: "#1a1b1d",
    topbar: "#101112",
    active: "#b23a48",
    text: "#ffffff",
    muted: "#c9cbcd",
    accent: "#ff6b7a",
  },
  {
    id: "protanopia-deuteranopia",
    name: "Protanopia & Deuteranopia",
    group: "Vision assistive",
    rail: "#3d1a52",
    sidebar: "#4d2167",
    topbar: "#3d1a52",
    active: "#2f6fd0",
    text: "#ffffff",
    muted: "#d6c6e2",
    accent: "#f0c419",
  },

  // ── Fun and new ──
  {
    id: "raspberry-beret",
    name: "Raspberry Beret",
    group: "Fun and new",
    rail: "#4a0f2b",
    sidebar: "#6b1440",
    topbar: "#4a0f2b",
    active: "#b4306c",
    text: "#ffffff",
    muted: "#e8c2d6",
    accent: "#ff7ab0",
  },
  {
    id: "big-business",
    name: "Big Business",
    group: "Fun and new",
    rail: "#111b3a",
    sidebar: "#1a274f",
    topbar: "#111b3a",
    active: "#3556a8",
    text: "#ffffff",
    muted: "#bcc6e2",
    accent: "#7f9dff",
  },
  {
    id: "pog",
    name: "POG",
    group: "Fun and new",
    rail: "#7a2f0c",
    sidebar: "#9c4110",
    topbar: "#7a2f0c",
    active: "#e07a2b",
    text: "#ffffff",
    muted: "#f2d0b6",
    accent: "#ffb765",
  },
  {
    id: "mint-chip",
    name: "Mint Chip",
    group: "Fun and new",
    rail: "#123a33",
    sidebar: "#1a5147",
    topbar: "#123a33",
    active: "#3fa88c",
    text: "#ffffff",
    muted: "#c2e3da",
    accent: "#7fe8c8",
  },
  {
    id: "pbj",
    name: "PB&J",
    group: "Fun and new",
    rail: "#4a1220",
    sidebar: "#63182b",
    topbar: "#4a1220",
    active: "#b8562f",
    text: "#ffffff",
    muted: "#e8c8c0",
    accent: "#f5a25d",
  },
  {
    id: "chill-vibes",
    name: "Chill Vibes",
    group: "Fun and new",
    rail: "#0d3b45",
    sidebar: "#124f5c",
    topbar: "#0d3b45",
    active: "#2a8f9e",
    text: "#ffffff",
    muted: "#bcdde2",
    accent: "#65d3e0",
  },
  {
    id: "forest-floor",
    name: "Forest Floor",
    group: "Fun and new",
    rail: "#26301a",
    sidebar: "#354224",
    topbar: "#26301a",
    active: "#6f8c3a",
    text: "#ffffff",
    muted: "#d2dcbf",
    accent: "#a8c96b",
  },
  {
    id: "slackr",
    name: "Slackr",
    group: "Fun and new",
    rail: "#4a1020",
    sidebar: "#62152b",
    topbar: "#4a1020",
    active: "#b02f4f",
    text: "#ffffff",
    muted: "#ecc4cf",
    accent: "#ff7d9c",
  },
  {
    id: "sea-glass",
    name: "Sea Glass",
    group: "Fun and new",
    rail: "#2a2350",
    sidebar: "#3a2f6b",
    topbar: "#2a2350",
    active: "#6f63bd",
    text: "#ffffff",
    muted: "#cfc9e8",
    accent: "#a99cf0",
  },
  {
    id: "lemon-lime",
    name: "Lemon Lime",
    group: "Fun and new",
    rail: "#3d3f0f",
    sidebar: "#535616",
    topbar: "#3d3f0f",
    active: "#9aa62c",
    text: "#ffffff",
    muted: "#e0e2b8",
    accent: "#d6e35c",
  },
  {
    id: "falling-leaves",
    name: "Falling Leaves",
    group: "Fun and new",
    rail: "#5c3a0d",
    sidebar: "#7a4e12",
    topbar: "#5c3a0d",
    active: "#c98a2b",
    text: "#ffffff",
    muted: "#ecd8b4",
    accent: "#ffc46b",
  },
  {
    id: "sunrise",
    name: "Sunrise",
    group: "Fun and new",
    rail: "#5c1020",
    sidebar: "#7d162c",
    topbar: "#5c1020",
    active: "#cf3b4f",
    text: "#ffffff",
    muted: "#eec3c9",
    accent: "#ff8f9c",
  },

  // ── Updated classics ──
  {
    id: "choco-mint",
    name: "Choco Mint",
    group: "Updated classics",
    rail: "#241a14",
    sidebar: "#33251c",
    topbar: "#241a14",
    active: "#3f8f78",
    text: "#ffffff",
    muted: "#d8cbc2",
    accent: "#7fdcc0",
  },
  {
    id: "cmyk",
    name: "CMYK",
    group: "Updated classics",
    rail: "#1a1a1a",
    sidebar: "#242424",
    topbar: "#1a1a1a",
    active: "#d6336c",
    text: "#ffffff",
    muted: "#c9c9c9",
    accent: "#22b8cf",
  },
  {
    id: "haberdashery",
    name: "Haberdashery",
    group: "Updated classics",
    rail: "#1f2430",
    sidebar: "#2b3141",
    topbar: "#1f2430",
    active: "#c2953c",
    text: "#ffffff",
    muted: "#c3c8d4",
    accent: "#e8c46b",
  },
  {
    id: "hoth",
    name: "Hoth",
    group: "Updated classics",
    rail: "#122234",
    sidebar: "#1b3149",
    topbar: "#122234",
    active: "#3a7fb5",
    text: "#ffffff",
    muted: "#c3d4e2",
    accent: "#7fc4ec",
  },
  {
    id: "ochin",
    name: "Ochin",
    group: "Updated classics",
    rail: "#1a2340",
    sidebar: "#243055",
    topbar: "#1a2340",
    active: "#4260a8",
    text: "#ffffff",
    muted: "#c4cbe0",
    accent: "#8aa3e8",
  },
  {
    id: "sweet-treat",
    name: "Sweet Treat",
    group: "Updated classics",
    rail: "#5c1226",
    sidebar: "#7a1a33",
    topbar: "#5c1226",
    active: "#c73f63",
    text: "#ffffff",
    muted: "#eec6d2",
    accent: "#ff8fae",
  },
];

export const DEFAULT_CHROME_THEME_ID = "aubergine";

export function getChromeTheme(id: string): ChromeTheme {
  return (
    CHROME_THEMES.find((t) => t.id === id) ??
    CHROME_THEMES.find((t) => t.id === DEFAULT_CHROME_THEME_ID)!
  );
}

/** CSS custom properties a theme overrides on top of the colour mode. */
export function chromeThemeVariables(theme: ChromeTheme): Record<string, string> {
  return {
    "--rail-bg": theme.rail,
    "--sidebar-bg": theme.sidebar,
    "--topbar-bg": theme.topbar,
    "--sidebar-active": theme.active,
    "--sidebar-text": theme.text,
    "--sidebar-muted": theme.muted,
    "--sidebar-accent": theme.accent,
  };
}
