export { chatReducer, initialState } from "./chat-reducer";
export type {
  ChatAction,
  ChatStoreState,
  WorkspaceInfo,
  DmConversation,
  GroupDmConversation,
  GroupDmMember,
  PresenceEntry,
  ScrollTarget,
  ChannelPaginationState,
  ThreadPaginationState,
} from "./chat-reducer";

export type { AuthProvider, StorageProvider } from "./platform";
export {
  AuthError,
  ApiError,
  getErrorMessage,
  authorizedHeaders,
  authorizedRequest,
  withRetry,
  createApiClient,
} from "./api";
export type { ApiClient } from "./api";

export { SocketManager } from "./socket";
export type {
  TypedSocket,
  SocketStatus,
  SocketSnapshot,
  SnapshotListener,
  TokenProvider,
} from "./socket";

export type { OperationDeps, ApiDeps } from "./operations";
export type { WorkspaceMember, ChannelMember, WorkspaceListItem, BrowseChannel, UserProfile, SavedMessageItem, ScheduledMessageItem, DraftItem, FetchFilesParams, FetchFilesResult, UserThreadItem } from "./operations";
export { normalizeChannel, normalizeDmConversation, normalizeGroupDmConversation } from "./operations/normalize";
export {
  bootstrapWorkspace,
  loadChannelMessages,
  loadOlderMessages,
  loadNewerMessages,
  loadThreadMessages,
  loadOlderReplies,
  loadMoreReplies,
  fetchUserThreads,
  toggleReaction,
  sendMessage,
  editMessage,
  deleteMessage,
  createDm,
  findOrCreateDmForCompose,
  createGroupDm,
  findOrCreateGroupDmForCompose,
  handlePresenceSync,
  handlePresenceUpdate,
  handleUserStatusUpdated,
  handleNewMessageUnread,
  markChannelAsRead,
  markChannelAsUnread,
  handleHuddleSync,
  handleHuddleStarted,
  handleHuddleUpdated,
  handleHuddleEnded,
  setCurrentHuddleChannel,
  notifyHuddleLeave,
  handleChannelMemberAdded,
  handleChannelMemberRemoved,
  createChannel,
  joinChannel,
  leaveChannel,
  browseChannels,
  updateChannelDescription,
  archiveChannel,
  unarchiveChannel,
  getInvite,
  acceptInvite,
  listInvites,
  createInvite,
  revokeInvite,
  listWorkspaceMembers,
  updateMemberRole,
  removeMember,
  leaveWorkspace,
  deleteWorkspace,
  checkAdmin,
  getStats,
  getActivity,
  getUsers,
  getAdminWorkspaces,
  impersonate,
  listChannelMembers,
  addChannelMember,
  addChannelMembersBulk,
  removeChannelMember,
  listWorkspaces,
  createWorkspace,
  searchMessages,
  fetchStarredChannels,
  starChannelOp,
  unstarChannelOp,
  pinMessageOp,
  unpinMessageOp,
  fetchPinnedMessages,
  fetchPinnedMessageCount,
  saveMessageOp,
  unsaveMessageOp,
  fetchSavedMessages,
  fetchSavedMessageIds,
  listBots,
  createBot,
  updateBot,
  deleteBot,
  regenerateBotToken,
  toggleBot,
  fetchChannelNotificationPrefs,
  setChannelNotificationPrefOp,
  getCurrentUser,
  updateCurrentUser,
  setUserStatus,
  clearUserStatus,
  handleUserProfileUpdated,
  fetchAllUnreads,
  markAllAsRead,
  shareMessageOp,
  createScheduledMessageOp,
  fetchScheduledMessages,
  fetchScheduledCountForChannel,
  updateScheduledMessageOp,
  deleteScheduledMessageOp,
  fetchDrafts,
  upsertDraftOp,
  deleteDraftOp,
  deleteDraftByKeyOp,
  fetchDraftForChannel,
  fetchFiles,
  fetchCustomEmojis,
  uploadCustomEmoji,
  deleteCustomEmoji,
  fetchBookmarks,
  fetchTabs,
  fetchCanvasContent,
  createTabOp,
  renameTabOp,
  saveCanvasOp,
  deleteTabOp,
  createDatabaseOp,
  fetchDatabase,
  updateDatabaseOp,
  createDatabaseRowOp,
  updateDatabaseRowOp,
  deleteDatabaseRowOp,
  fetchSavedItemIds,
  saveFolderItemOp,
  unsaveFolderItemOp,
  fetchSavedFolderItems,
  addBookmarkOp,
  removeBookmarkOp,
  registerPushToken,
  unregisterPushToken,
  registerVoipToken,
  unregisterVoipToken,
  getGlobalNotificationPrefs,
  updateGlobalNotificationPrefs,
  fetchSlashCommands,
  executeSlashCommand,
  listApiKeys,
  createApiKey,
  deleteApiKey,
  listMarketplaceListings,
  getMarketplaceListing,
  installMarketplaceListing,
  uninstallMarketplaceListing,
  getInstalledListings,
  getFeatureFlags,
  getAdminFeatureFlags,
  updateAdminFeatureFlags,
  bulkUpdateFeatureFlag,
  fetchUserGroups,
  fetchUserGroup,
  fetchGroupSections,
  createUserGroup,
  updateUserGroup,
  deleteUserGroup,
  addUserGroupMembers,
  removeUserGroupMember,
  addUserGroupChannels,
  removeUserGroupChannel,
  fetchPages,
  fetchPage,
  createPageOp,
  updatePageOp,
  movePageOp,
  archivePageOp,
  favouritePageOp,
  buildPageTree,
  ensureTabPageOp,
} from "./operations";
export type { PageNode } from "./operations";

export {
  STATUS_PRESETS,
  DURATION_OPTIONS,
  DURATION_LABELS,
  durationToExpiresAt,
} from "./status-presets";
export type { StatusPreset, DurationOption } from "./status-presets";

export { useSocketEvent, useOnlineStatus } from "./hooks";

export {
  isCustomEmojiShortcode,
  parseCustomEmojiName,
  buildCustomEmojiShortcode,
  findCustomEmoji,
} from "./emoji-utils";
